import type { Job, Application, Interview, Email, ContentCalendarEntry } from "./schema";

export const mockJobs: Job[] = [
  {
    id: "a1b2c3d4-0001-4000-8000-000000000001",
    tenantId: "t-0001",
    title: "Senior L&D Consultant",
    company: "Deloitte",
    location: "London, UK",
    url: "https://example.com/job/1",
    source: "reed",
    description: "Lead learning and development strategy for enterprise clients.",
    tier: "A+",
    compositeScore: "92",
    status: "new",
    jobType: "permanent",
    salaryMin: "65000",
    salaryMax: "85000",
    discoveredAt: new Date("2026-04-03T08:00:00Z"),
    readyToApply: true,
    cvPackageStatus: "ready",
  },
  {
    id: "a1b2c3d4-0002-4000-8000-000000000002",
    tenantId: "t-0001",
    title: "Learning Experience Designer",
    company: "BBC",
    location: "Manchester, UK",
    url: "https://example.com/job/2",
    source: "adzuna",
    description: "Design digital learning experiences for internal teams.",
    tier: "A",
    compositeScore: "87",
    status: "new",
    jobType: "permanent",
    salaryMin: "55000",
    salaryMax: "70000",
    discoveredAt: new Date("2026-04-03T09:30:00Z"),
    readyToApply: false,
    cvPackageStatus: "pending",
  },
  {
    id: "a1b2c3d4-0003-4000-8000-000000000003",
    tenantId: "t-0001",
    title: "Head of People Development",
    company: "Revolut",
    location: "London, UK (Hybrid)",
    url: "https://example.com/job/3",
    source: "reed",
    description: "Own the people development function across EMEA.",
    tier: "A+",
    compositeScore: "95",
    status: "scored",
    jobType: "permanent",
    salaryMin: "90000",
    salaryMax: "120000",
    discoveredAt: new Date("2026-04-02T14:00:00Z"),
    readyToApply: true,
    cvPackageStatus: "ready",
  },
  {
    id: "a1b2c3d4-0004-4000-8000-000000000004",
    tenantId: "t-0001",
    title: "Training Manager",
    company: "NHS England",
    location: "Leeds, UK",
    url: "https://example.com/job/4",
    source: "rss",
    description: "Manage training programs for clinical staff.",
    tier: "B",
    compositeScore: "72",
    status: "new",
    jobType: "permanent",
    salaryMin: "45000",
    salaryMax: "55000",
    discoveredAt: new Date("2026-04-03T11:00:00Z"),
    readyToApply: false,
    cvPackageStatus: null,
  },
  {
    id: "a1b2c3d4-0005-4000-8000-000000000005",
    tenantId: "t-0001",
    title: "Organisational Development Specialist",
    company: "Unilever",
    location: "London, UK",
    url: "https://example.com/job/5",
    source: "adzuna",
    description: "Drive OD initiatives across the UK business.",
    tier: "A",
    compositeScore: "84",
    status: "cv_ready",
    jobType: "contract",
    salaryMin: "400",
    salaryMax: "550",
    discoveredAt: new Date("2026-04-01T16:00:00Z"),
    readyToApply: true,
    cvPackageStatus: "ready",
  },
  {
    id: "a1b2c3d4-0006-4000-8000-000000000006",
    tenantId: "t-0001",
    title: "Junior HR Coordinator",
    company: "Local Council",
    location: "Birmingham, UK",
    url: "https://example.com/job/6",
    source: "rss",
    description: "Support the HR team with admin tasks.",
    tier: "C",
    compositeScore: "45",
    status: "new",
    jobType: "permanent",
    salaryMin: "25000",
    salaryMax: "30000",
    discoveredAt: new Date("2026-04-03T07:00:00Z"),
    readyToApply: false,
    cvPackageStatus: null,
  },
  {
    id: "a1b2c3d4-0007-4000-8000-000000000007",
    tenantId: "t-0001",
    title: "Digital Learning Lead",
    company: "PwC",
    location: "London, UK",
    url: "https://example.com/job/7",
    source: "reed",
    description: "Lead the digital learning transformation program.",
    tier: "A",
    compositeScore: "88",
    status: "applied",
    jobType: "permanent",
    salaryMin: "70000",
    salaryMax: "90000",
    discoveredAt: new Date("2026-03-30T10:00:00Z"),
    readyToApply: true,
    cvPackageStatus: "ready",
  },
];

export const mockApplications: Application[] = [
  {
    id: "b1b2c3d4-0001-4000-8000-000000000001",
    tenantId: "t-0001",
    jobId: "a1b2c3d4-0007-4000-8000-000000000007",
    companyName: "PwC",
    jobTitle: "Digital Learning Lead",
    pipelineTrack: "direct_apply",
    currentState: "applied",
    appliedAt: new Date("2026-03-31T09:00:00Z"),
    followUpCount: 1,
    nextFollowUpAt: new Date("2026-04-07T09:00:00Z"),
    interviewCount: 0,
    discoverySource: "reed",
    isActive: true,
  },
  {
    id: "b1b2c3d4-0002-4000-8000-000000000002",
    tenantId: "t-0001",
    jobId: null,
    companyName: "KPMG",
    jobTitle: "L&D Business Partner",
    pipelineTrack: "recruiter",
    currentState: "interviewing",
    appliedAt: new Date("2026-03-25T14:00:00Z"),
    followUpCount: 2,
    nextFollowUpAt: null,
    interviewCount: 2,
    discoverySource: "adzuna",
    isActive: true,
  },
  {
    id: "b1b2c3d4-0003-4000-8000-000000000003",
    tenantId: "t-0001",
    jobId: null,
    companyName: "Shell",
    jobTitle: "Leadership Development Manager",
    pipelineTrack: "direct_apply",
    currentState: "ghosted",
    appliedAt: new Date("2026-03-15T10:00:00Z"),
    followUpCount: 3,
    nextFollowUpAt: new Date("2026-04-05T10:00:00Z"),
    interviewCount: 0,
    discoverySource: "reed",
    isActive: true,
  },
  {
    id: "b1b2c3d4-0004-4000-8000-000000000004",
    tenantId: "t-0001",
    jobId: null,
    companyName: "Google",
    jobTitle: "People Development Lead",
    pipelineTrack: "referral",
    currentState: "offered",
    appliedAt: new Date("2026-03-10T11:00:00Z"),
    followUpCount: 0,
    nextFollowUpAt: null,
    interviewCount: 3,
    discoverySource: "referral",
    isActive: true,
  },
  {
    id: "b1b2c3d4-0005-4000-8000-000000000005",
    tenantId: "t-0001",
    jobId: null,
    companyName: "Barclays",
    jobTitle: "Talent Development Manager",
    pipelineTrack: "direct_apply",
    currentState: "applied",
    appliedAt: new Date("2026-04-01T10:00:00Z"),
    followUpCount: 0,
    nextFollowUpAt: new Date("2026-04-08T10:00:00Z"),
    interviewCount: 0,
    discoverySource: "adzuna",
    isActive: true,
  },
  {
    id: "b1b2c3d4-0006-4000-8000-000000000006",
    tenantId: "t-0001",
    jobId: null,
    companyName: "Accenture",
    jobTitle: "Learning Architect",
    pipelineTrack: "recruiter",
    currentState: "acknowledged",
    appliedAt: new Date("2026-03-28T15:00:00Z"),
    followUpCount: 0,
    nextFollowUpAt: null,
    interviewCount: 0,
    discoverySource: "reed",
    isActive: true,
  },
  {
    id: "b1b2c3d4-0007-4000-8000-000000000007",
    tenantId: "t-0001",
    jobId: null,
    companyName: "Meta",
    jobTitle: "People Programs Lead",
    pipelineTrack: "referral",
    currentState: "interviewing",
    appliedAt: new Date("2026-03-20T09:00:00Z"),
    followUpCount: 1,
    nextFollowUpAt: null,
    interviewCount: 1,
    discoverySource: "referral",
    isActive: true,
  },
  {
    id: "b1b2c3d4-0008-4000-8000-000000000008",
    tenantId: "t-0001",
    jobId: null,
    companyName: "Lloyds Banking Group",
    jobTitle: "Senior L&D Consultant",
    pipelineTrack: "direct_apply",
    currentState: "rejected",
    appliedAt: new Date("2026-03-12T11:00:00Z"),
    followUpCount: 1,
    nextFollowUpAt: null,
    interviewCount: 1,
    discoverySource: "adzuna",
    isActive: false,
  },
  {
    id: "b1b2c3d4-0009-4000-8000-000000000009",
    tenantId: "t-0001",
    jobId: null,
    companyName: "Amazon",
    jobTitle: "Leadership Development Lead",
    pipelineTrack: "direct_apply",
    currentState: "applied",
    appliedAt: new Date("2026-04-02T08:00:00Z"),
    followUpCount: 0,
    nextFollowUpAt: new Date("2026-04-09T08:00:00Z"),
    interviewCount: 0,
    discoverySource: "reed",
    isActive: true,
  },
  {
    id: "b1b2c3d4-0010-4000-8000-000000000010",
    tenantId: "t-0001",
    jobId: null,
    companyName: "Acme Corp",
    jobTitle: "Training Specialist",
    pipelineTrack: "direct_apply",
    currentState: "ghosted",
    appliedAt: new Date("2026-03-08T14:00:00Z"),
    followUpCount: 2,
    nextFollowUpAt: new Date("2026-04-06T14:00:00Z"),
    interviewCount: 0,
    discoverySource: "rss",
    isActive: true,
  },
];

export const mockInterviews: Interview[] = [
  {
    id: "c1b2c3d4-0001-4000-8000-000000000001",
    tenantId: "t-0001",
    companyName: "KPMG",
    roleTitle: "L&D Business Partner",
    interviewTrack: "standard",
    interviewFormat: "competency",
    interviewDate: new Date("2026-04-07T10:00:00Z"),
    interviewStartTime: "10:00",
    status: "scheduled",
    locationType: "video",
    videoLink: "https://teams.microsoft.com/meet/abc123",
    physicalAddress: null,
  },
  {
    id: "c1b2c3d4-0002-4000-8000-000000000002",
    tenantId: "t-0001",
    companyName: "Google",
    roleTitle: "People Development Lead",
    interviewTrack: "executive",
    interviewFormat: "case_study",
    interviewDate: new Date("2026-04-09T14:00:00Z"),
    interviewStartTime: "14:00",
    status: "scheduled",
    locationType: "in_person",
    videoLink: null,
    physicalAddress: "6 Pancras Square, London N1C 4AG",
  },
  {
    id: "c1b2c3d4-0003-4000-8000-000000000003",
    tenantId: "t-0001",
    companyName: "Meta",
    roleTitle: "People Programs Lead",
    interviewTrack: "standard",
    interviewFormat: "behavioral",
    interviewDate: new Date("2026-04-11T11:00:00Z"),
    interviewStartTime: "11:00",
    status: "scheduled",
    locationType: "video",
    videoLink: "https://zoom.us/j/1234567890",
    physicalAddress: null,
  },
  {
    id: "c1b2c3d4-0004-4000-8000-000000000004",
    tenantId: "t-0001",
    companyName: "Barclays",
    roleTitle: "Talent Development Manager",
    interviewTrack: "standard",
    interviewFormat: "panel",
    interviewDate: new Date("2026-04-14T09:30:00Z"),
    interviewStartTime: "09:30",
    status: "scheduled",
    locationType: "in_person",
    videoLink: null,
    physicalAddress: "1 Churchill Place, London E14 5HP",
  },
];

export const mockEmails: (Email & { classification?: string; isUrgent?: boolean })[] = [
  {
    id: "e001", tenantId: "t-0001",
    subject: "Interview Invitation - L&D Business Partner",
    fromEmail: "recruitment@kpmg.co.uk", fromName: "KPMG Recruitment",
    date: new Date("2026-04-03T09:15:00Z"), status: "read",
    isJobRelated: true, classification: "interview_invitation", isUrgent: true,
  },
  {
    id: "e002", tenantId: "t-0001",
    subject: "Your application for People Development Lead",
    fromEmail: "noreply@google.com", fromName: "Google Careers",
    date: new Date("2026-04-03T08:00:00Z"), status: "read",
    isJobRelated: true, classification: "interview_invitation", isUrgent: true,
  },
  {
    id: "e003", tenantId: "t-0001",
    subject: "Exciting L&D opportunity - are you interested?",
    fromEmail: "james.r@hays.com", fromName: "James Roberts - Hays",
    date: new Date("2026-04-02T16:30:00Z"), status: "unread",
    isJobRelated: true, classification: "recruiter_outreach", isUrgent: false,
  },
  {
    id: "e004", tenantId: "t-0001",
    subject: "Re: Senior Learning Consultant - contract role",
    fromEmail: "sarah.m@robertwalters.com", fromName: "Sarah Mitchell - Robert Walters",
    date: new Date("2026-04-02T14:00:00Z"), status: "unread",
    isJobRelated: true, classification: "recruiter_outreach", isUrgent: false,
  },
  {
    id: "e005", tenantId: "t-0001",
    subject: "Application received - Digital Learning Lead",
    fromEmail: "careers@pwc.com", fromName: "PwC Careers",
    date: new Date("2026-03-31T10:00:00Z"), status: "read",
    isJobRelated: true, classification: "acknowledgement", isUrgent: false,
  },
  {
    id: "e006", tenantId: "t-0001",
    subject: "Thank you for your application - Training Specialist",
    fromEmail: "hr@acmecorp.com", fromName: "Acme Corp HR",
    date: new Date("2026-03-28T09:00:00Z"), status: "read",
    isJobRelated: true, classification: "acknowledgement", isUrgent: false,
  },
  {
    id: "e007", tenantId: "t-0001",
    subject: "Application update - Senior L&D Consultant",
    fromEmail: "recruitment@lloydsbanking.com", fromName: "Lloyds Banking Group",
    date: new Date("2026-03-30T15:00:00Z"), status: "read",
    isJobRelated: true, classification: "rejection", isUrgent: false,
  },
  {
    id: "e008", tenantId: "t-0001",
    subject: "Unfortunately, your application was not successful",
    fromEmail: "noreply@bp.com", fromName: "BP Careers",
    date: new Date("2026-03-29T11:00:00Z"), status: "read",
    isJobRelated: true, classification: "rejection", isUrgent: false,
  },
  {
    id: "e009", tenantId: "t-0001",
    subject: "New jobs matching your search: L&D Manager",
    fromEmail: "alerts@reed.co.uk", fromName: "Reed Job Alerts",
    date: new Date("2026-04-03T07:00:00Z"), status: "unread",
    isJobRelated: true, classification: "job_alert", isUrgent: false,
  },
  {
    id: "e010", tenantId: "t-0001",
    subject: "12 new L&D jobs in London this week",
    fromEmail: "alerts@adzuna.co.uk", fromName: "Adzuna Weekly",
    date: new Date("2026-04-02T06:00:00Z"), status: "read",
    isJobRelated: true, classification: "job_alert", isUrgent: false,
  },
  {
    id: "e011", tenantId: "t-0001",
    subject: "Leadership & Development roles - weekly digest",
    fromEmail: "digest@linkedin.com", fromName: "LinkedIn Jobs",
    date: new Date("2026-04-01T07:00:00Z"), status: "read",
    isJobRelated: true, classification: "job_alert", isUrgent: false,
  },
  {
    id: "e012", tenantId: "t-0001",
    subject: "Re: People Programs Lead - next steps",
    fromEmail: "talent@meta.com", fromName: "Meta Talent Team",
    date: new Date("2026-04-03T10:45:00Z"), status: "unread",
    isJobRelated: true, classification: "interview_invitation", isUrgent: true,
  },
  {
    id: "e013", tenantId: "t-0001",
    subject: "Application received - Leadership Development Lead",
    fromEmail: "jobs@amazon.co.uk", fromName: "Amazon Jobs UK",
    date: new Date("2026-04-02T09:00:00Z"), status: "read",
    isJobRelated: true, classification: "acknowledgement", isUrgent: false,
  },
  {
    id: "e014", tenantId: "t-0001",
    subject: "We'd love to connect about OD roles",
    fromEmail: "lisa.k@michaelpage.com", fromName: "Lisa King - Michael Page",
    date: new Date("2026-04-01T13:00:00Z"), status: "unread",
    isJobRelated: true, classification: "recruiter_outreach", isUrgent: false,
  },
];

export const mockFunnelData = {
  discovered: 142,
  scored: 89,
  cvReady: 34,
  applied: 12,
  interviewing: 3,
  offered: 1,
};

export const mockStats = {
  totalActiveJobs: 47,
  applicationsThisWeek: 4,
  responseRate: 25,
  upcomingInterviews: 2,
};

export const mockNotifications = [
  {
    id: "n1",
    title: "Interview invite from Barclays",
    description: "Talent Development Manager - Panel interview on Apr 14",
    time: "2 hours ago",
    type: "interview" as const,
  },
  {
    id: "n2",
    title: "CV ready for Deloitte role",
    description: "Senior L&D Consultant - tailored CV package generated",
    time: "5 hours ago",
    type: "cv" as const,
  },
  {
    id: "n3",
    title: "Follow-up due: Acme Corp",
    description: "Training Specialist - no response after 27 days",
    time: "1 day ago",
    type: "followup" as const,
  },
];

export const mockMetricsWeekly = [
  { week: "W9", responseRate: 18, applications: 3, ghostingRate: 40, sourceDirect: 2, sourceRecruiter: 1, sourceReferral: 0 },
  { week: "W10", responseRate: 22, applications: 5, ghostingRate: 35, sourceDirect: 3, sourceRecruiter: 1, sourceReferral: 1 },
  { week: "W11", responseRate: 20, applications: 4, ghostingRate: 38, sourceDirect: 2, sourceRecruiter: 2, sourceReferral: 0 },
  { week: "W12", responseRate: 28, applications: 6, ghostingRate: 30, sourceDirect: 3, sourceRecruiter: 2, sourceReferral: 1 },
  { week: "W13", responseRate: 25, applications: 4, ghostingRate: 32, sourceDirect: 2, sourceRecruiter: 1, sourceReferral: 1 },
  { week: "W14", responseRate: 30, applications: 5, ghostingRate: 28, sourceDirect: 2, sourceRecruiter: 2, sourceReferral: 1 },
  { week: "W15", responseRate: 33, applications: 7, ghostingRate: 22, sourceDirect: 4, sourceRecruiter: 2, sourceReferral: 1 },
  { week: "W16", responseRate: 35, applications: 4, ghostingRate: 20, sourceDirect: 2, sourceRecruiter: 1, sourceReferral: 1 },
];

export const mockSourceData = [
  { source: "Reed", count: 18 },
  { source: "Adzuna", count: 14 },
  { source: "LinkedIn", count: 8 },
  { source: "Referral", count: 5 },
  { source: "RSS Feeds", count: 3 },
];

export const mockPipelineFunnel = [
  { stage: "Discovered", count: 142 },
  { stage: "Scored", count: 89 },
  { stage: "CV Ready", count: 34 },
  { stage: "Applied", count: 12 },
  { stage: "Interviewing", count: 3 },
  { stage: "Offered", count: 1 },
];

export const mockLinkedInContent: ContentCalendarEntry[] = [
  {
    id: "lc001", tenantId: "t-0001",
    topicTitle: "Why L&D Metrics That Matter Aren't the Ones We Track",
    contentPillar: "thought_leadership",
    draftText: "Most L&D teams track completion rates and satisfaction scores. But the metrics that actually drive business impact are different...",
    status: "drafted",
    suggestedPostDay: "Monday",
  },
  {
    id: "lc002", tenantId: "t-0001",
    topicTitle: "5 Signs Your Onboarding Programme Needs a Redesign",
    contentPillar: "practical_tips",
    draftText: "After redesigning onboarding for 3 organisations last year, I noticed the same five warning signs kept showing up...",
    status: "planned",
    suggestedPostDay: "Wednesday",
  },
  {
    id: "lc003", tenantId: "t-0001",
    topicTitle: "The Future of Workplace Learning is Already Here",
    contentPillar: "industry_trends",
    draftText: "AI-powered personalised learning paths. Microlearning integrated into workflow. Peer coaching at scale. These aren't future predictions -- they're happening now...",
    status: "published",
    suggestedPostDay: "Friday",
  },
];

export const mockLinkedInProfile = {
  completenessScore: 82,
  recentViews: 47,
  alignmentIssues: [
    {
      id: "ai1",
      issue: "Headline doesn't mention 'L&D' or 'Learning & Development' explicitly",
      severity: "high" as const,
      snoozedUntil: null as Date | null,
    },
    {
      id: "ai2",
      issue: "Skills section missing 'Instructional Design' and 'Talent Development'",
      severity: "medium" as const,
      snoozedUntil: null as Date | null,
    },
    {
      id: "ai3",
      issue: "About section could better highlight quantified achievements",
      severity: "medium" as const,
      snoozedUntil: null as Date | null,
    },
  ],
  recommendations: [
    {
      id: "rec1",
      area: "Headline",
      suggestion: "Add 'CIPD Qualified' to headline",
      current: "Senior People Development Professional | Passionate About Growth",
      proposed: "Senior L&D Leader | CIPD Qualified | People Development & Organisational Transformation",
      status: "pending" as const,
    },
    {
      id: "rec2",
      area: "Skills",
      suggestion: "Add 'Instructional Design' to skills section",
      current: "(not listed)",
      proposed: "Instructional Design",
      status: "pending" as const,
    },
    {
      id: "rec3",
      area: "Skills",
      suggestion: "Add 'Talent Development' to skills section",
      current: "(not listed)",
      proposed: "Talent Development",
      status: "pending" as const,
    },
    {
      id: "rec4",
      area: "About",
      suggestion: "Lead with a quantified achievement",
      current: "I'm passionate about helping organisations develop their people...",
      proposed: "Over 10 years, I've designed L&D programmes that improved retention by 34% and boosted internal promotion rates by 22% across 5 FTSE 100 organisations.",
      status: "pending" as const,
    },
    {
      id: "rec5",
      area: "Experience",
      suggestion: "Add measurable outcomes to current role",
      current: "Led various training programmes for the business.",
      proposed: "Designed and delivered a leadership programme for 200+ managers, resulting in a 28% improvement in 360-feedback scores within 6 months.",
      status: "pending" as const,
    },
    {
      id: "rec6",
      area: "Featured",
      suggestion: "Add a featured post about L&D strategy",
      current: "(empty)",
      proposed: "Pin your top-performing LinkedIn post or a link to a published article/case study.",
      status: "pending" as const,
    },
  ],
  suggestedHashtags: [
    { tag: "#LearningAndDevelopment", selected: true },
    { tag: "#PeopleDevelopment", selected: true },
    { tag: "#CIPD", selected: true },
    { tag: "#TalentDevelopment", selected: false },
    { tag: "#OrganisationalDevelopment", selected: false },
    { tag: "#LeadershipDevelopment", selected: true },
    { tag: "#FutureOfWork", selected: false },
    { tag: "#HRTech", selected: false },
  ],
};

export const mockEmailExtractedDetails: Record<string, {
  interviewDate?: string;
  interviewTime?: string;
  interviewLocation?: string;
  interviewFormat?: string;
  roleTitle?: string;
  company?: string;
  jobLinks?: { title: string; url: string }[];
  recruiterNote?: string;
}> = {
  e001: {
    interviewDate: "7 April 2026",
    interviewTime: "10:00 AM",
    interviewLocation: "Microsoft Teams",
    interviewFormat: "Competency-based",
    roleTitle: "L&D Business Partner",
    company: "KPMG",
  },
  e002: {
    interviewDate: "9 April 2026",
    interviewTime: "2:00 PM",
    interviewLocation: "6 Pancras Square, London N1C 4AG",
    interviewFormat: "Case Study",
    roleTitle: "People Development Lead",
    company: "Google",
  },
  e003: {
    recruiterNote: "Looking for a senior L&D professional for a FTSE 250 financial services client. 6-month contract, inside IR35, up to 500/day.",
    roleTitle: "Senior L&D Consultant",
    company: "Confidential (FTSE 250 Financial Services)",
  },
  e004: {
    recruiterNote: "Following up on our conversation last week. The client loved your profile. They'd like to arrange a call this week.",
    roleTitle: "Senior Learning Consultant",
    company: "Major UK Retailer",
  },
  e009: {
    jobLinks: [
      { title: "L&D Manager - BT Group", url: "https://reed.co.uk/jobs/123" },
      { title: "Learning Lead - Vodafone", url: "https://reed.co.uk/jobs/124" },
      { title: "Training Manager - Tesco", url: "https://reed.co.uk/jobs/125" },
    ],
  },
  e010: {
    jobLinks: [
      { title: "Head of L&D - Santander UK", url: "https://adzuna.co.uk/jobs/201" },
      { title: "OD Specialist - NatWest", url: "https://adzuna.co.uk/jobs/202" },
      { title: "L&D Partner - Sage", url: "https://adzuna.co.uk/jobs/203" },
      { title: "Learning Designer - Sky", url: "https://adzuna.co.uk/jobs/204" },
    ],
  },
  e011: {
    jobLinks: [
      { title: "People Development Manager - Spotify", url: "https://linkedin.com/jobs/301" },
      { title: "L&D Director - Canva", url: "https://linkedin.com/jobs/302" },
    ],
  },
  e012: {
    interviewDate: "11 April 2026",
    interviewTime: "11:00 AM",
    interviewLocation: "Zoom",
    interviewFormat: "Behavioural",
    roleTitle: "People Programs Lead",
    company: "Meta",
  },
  e014: {
    recruiterNote: "Several OD and L&D roles across London. Flexible on start date and open to both contract and permanent candidates.",
    roleTitle: "Various OD/L&D Roles",
    company: "Multiple Clients",
  },
};

export const mockMetricGoals = {
  applicationsPerWeek: { target: 10, actual: 4 },
  responseRate: { target: 40, actual: 35 },
  interviewsPerMonth: { target: 8, actual: 4 },
  offersPerQuarter: { target: 2, actual: 1 },
};

export const mockMetricInsights = [
  { text: "Your Reed applications get 3x more responses than Adzuna applications.", trend: "positive" as const },
  { text: "Response rate improved from 18% to 35% over the last 8 weeks.", trend: "positive" as const },
  { text: "Ghosting rate dropped 50% since you started follow-up automation.", trend: "positive" as const },
  { text: "Referral applications have a 60% interview conversion rate vs 15% for direct apply.", trend: "neutral" as const },
  { text: "You average 4.9 applications/week, below your target of 10.", trend: "negative" as const },
];

export const mockInterviewDebriefs: Record<string, {
  outcome: "progressed" | "rejected" | "pending" | "offered";
  notes: string;
  date: Date;
}> = {};

export const mockPastInterviews: typeof mockInterviews = [
  {
    id: "c1b2c3d4-0010-4000-8000-000000000010",
    tenantId: "t-0001",
    companyName: "Lloyds Banking Group",
    roleTitle: "Senior L&D Consultant",
    interviewTrack: "standard",
    interviewFormat: "competency",
    interviewDate: new Date("2026-03-20T10:00:00Z"),
    interviewStartTime: "10:00",
    status: "completed",
    locationType: "video",
    videoLink: null,
    physicalAddress: null,
  },
  {
    id: "c1b2c3d4-0011-4000-8000-000000000011",
    tenantId: "t-0001",
    companyName: "BP",
    roleTitle: "Learning Programme Manager",
    interviewTrack: "standard",
    interviewFormat: "behavioral",
    interviewDate: new Date("2026-03-18T14:00:00Z"),
    interviewStartTime: "14:00",
    status: "completed",
    locationType: "phone",
    videoLink: null,
    physicalAddress: null,
  },
];

export const mockSettings = {
  profile: {
    name: "Selvi Chellamma",
    email: "chellamma.uk@gmail.com",
    phone: "+44 7700 900000",
    location: "London, UK",
    salaryRange: "60,000 - 90,000 GBP",
    noticePeriod: "1 month",
  },
  searchConfig: {
    searchTerms: [
      "L&D Manager",
      "Learning & Development",
      "People Development",
      "Talent Development",
      "Organisational Development",
      "Training Manager",
    ],
    locations: ["London", "Manchester", "Remote UK"],
    salaryMin: 60000,
    salaryMax: 90000,
    sources: ["Reed", "Adzuna", "RSS Feeds", "LinkedIn"],
    tierThresholds: {
      "A+": "90-100",
      A: "80-89",
      B: "65-79",
      C: "Below 65",
    },
  },
  notifications: {
    emailEnabled: true,
    recipient: "chellamma.uk@gmail.com",
    digestTime: "07:30",
    quietHoursStart: "22:00",
    quietHoursEnd: "07:00",
    urgentBypassQuietHours: true,
  },
  connectedAccounts: {
    gmail: { connected: true, email: "chellamma.uk@gmail.com" },
    linkedin: { connected: true, profile: "linkedin.com/in/selvi-chellamma" },
  },
  workflows: [
    { name: "WF2a: Adzuna Poller", id: "9SEqwV5wggAtEqh7", status: "active" },
    { name: "WF2b: Reed Poller", id: "wjHyL60WKQUKT5jR", status: "active" },
    { name: "WF1: RSS Poller", id: "1UpSvlEjPCdsZQsg", status: "active" },
    { name: "WF5: AI Scoring", id: "Lyn8XzHQpSz1hjYa", status: "active" },
    { name: "WF6: Dedup & Cleanup", id: "Enk5MDTwxi0zHjzS", status: "active" },
    { name: "WF7: Daily Digest", id: "zJHAtZgCWvj2IDTw", status: "active" },
    { name: "WF4-GHOST: Ghosting Detection", id: "RjELbd8jHpE0mYLy", status: "active" },
    { name: "WF4-METRICS: Pipeline Metrics", id: "2jJ6mnhGDUUdMv4Q", status: "active" },
    { name: "WF4-NOTIFY: Notification Queue", id: "QYAJabWbPCEoCP5M", status: "active" },
    { name: "WF4-REPORT: Weekly Report", id: "6waaDhblGVkSqQ7R", status: "active" },
    { name: "WF5-INGEST: Email Ingestion", id: "dMJ3vwd4x8LwkJfh", status: "active" },
    { name: "WF5-CLASSIFY: Email Classification", id: "Jmndt4AUM1okHmDV", status: "active" },
    { name: "WF5-EXTRACT: Data Extraction", id: "OXkCaYer4oyRvpho", status: "active" },
    { name: "WF5-NOTIFY: Urgent Notification", id: "LDzddhyhIOlFBiq1", status: "active" },
    { name: "WF8: CV Tailoring Pipeline", id: "yPheY04xrwGA8EVW", status: "active" },
    { name: "WF-AP1: Application Router", id: "uXGKRhtdMPq9LJbH", status: "active" },
    { name: "WF7-CONTENT: LinkedIn Content", id: "mXpByVRapQef77PX", status: "active" },
    { name: "WF7-INTEL: Intelligence Digest", id: "KBKhzcxNN9yXcX21", status: "active" },
    { name: "WF7-ALIGNMENT: Profile Alignment", id: "htUY822cvSHeY6EW", status: "active" },
    { name: "WF6-PREP: Interview Prep", id: "c22XxluRJOWGj4RW", status: "active" },
    { name: "WF6-DAILY: Daily Briefing", id: "VGi4OAdRy3rOP2e9", status: "active" },
    { name: "WF6-FOLLOWUP: Post-Interview", id: "u16sM5nWU7lggkqh", status: "active" },
  ],
};

// --- New mock data for enhanced features ---

export const mockAiActivity = {
  lastScanTime: "23 min ago",
  lastScanDate: new Date("2026-04-04T08:37:00Z"),
  todaySummary: {
    jobsFound: 12,
    cvsTailored: 4,
    ghostedDetected: 2,
    emailsClassified: 8,
    followUpsSent: 1,
  },
  recentActions: [
    { time: "08:37", action: "Scanned Reed & Adzuna -- found 12 new jobs, 3 A-tier" },
    { time: "08:35", action: "Generated CV package for Deloitte Senior L&D Consultant" },
    { time: "08:30", action: "Classified 8 emails: 2 interview invites, 3 recruiter outreach" },
    { time: "07:30", action: "Sent daily digest to chellamma.uk@gmail.com" },
    { time: "06:00", action: "Pipeline metrics recalculated -- response rate up 5%" },
    { time: "02:00", action: "Ghosting detection ran: Shell (20 days), Acme Corp (27 days)" },
  ],
};

export const mockCvPackages = [
  {
    id: "cv-001",
    jobId: "a1b2c3d4-0001-4000-8000-000000000001",
    jobTitle: "Senior L&D Consultant",
    company: "Deloitte",
    cvType: "tailored",
    matchPercentage: 92,
    status: "ready" as const,
    createdAt: new Date("2026-04-03T08:35:00Z"),
    highlights: ["10+ years L&D leadership", "Enterprise client management", "Change management"],
  },
  {
    id: "cv-002",
    jobId: "a1b2c3d4-0003-4000-8000-000000000003",
    jobTitle: "Head of People Development",
    company: "Revolut",
    cvType: "executive",
    matchPercentage: 95,
    status: "ready" as const,
    createdAt: new Date("2026-04-02T14:30:00Z"),
    highlights: ["EMEA experience", "Fintech industry", "People strategy"],
  },
  {
    id: "cv-003",
    jobId: "a1b2c3d4-0005-4000-8000-000000000005",
    jobTitle: "Organisational Development Specialist",
    company: "Unilever",
    cvType: "tailored",
    matchPercentage: 84,
    status: "ready" as const,
    createdAt: new Date("2026-04-01T16:30:00Z"),
    highlights: ["OD frameworks", "Culture transformation", "FMCG experience"],
  },
  {
    id: "cv-004",
    jobId: "a1b2c3d4-0007-4000-8000-000000000007",
    jobTitle: "Digital Learning Lead",
    company: "PwC",
    cvType: "tailored",
    matchPercentage: 88,
    status: "sent" as const,
    createdAt: new Date("2026-03-30T10:30:00Z"),
    highlights: ["LMS implementation", "Digital transformation", "Big 4 consulting"],
  },
  {
    id: "cv-005",
    jobId: "a1b2c3d4-0002-4000-8000-000000000002",
    jobTitle: "Learning Experience Designer",
    company: "BBC",
    cvType: "tailored",
    matchPercentage: 87,
    status: "generating" as const,
    createdAt: new Date("2026-04-03T10:00:00Z"),
    highlights: ["Digital learning design", "Media industry", "User-centred design"],
  },
  {
    id: "cv-006",
    jobId: null,
    jobTitle: "L&D Business Partner",
    company: "KPMG",
    cvType: "tailored",
    matchPercentage: 85,
    status: "sent" as const,
    createdAt: new Date("2026-03-24T09:00:00Z"),
    highlights: ["Business partnering", "Strategic L&D", "Professional services"],
  },
];

export const mockApplicationTimeline: Record<string, {
  events: { date: Date; type: string; title: string; description: string }[];
  notes: { id: string; date: Date; text: string }[];
  documents: { name: string; type: string; url: string }[];
}> = {
  "b1b2c3d4-0001-4000-8000-000000000001": {
    events: [
      { date: new Date("2026-03-30T10:00:00Z"), type: "discovery", title: "Job discovered", description: "Found via Reed -- scored 88 (A tier)" },
      { date: new Date("2026-03-30T10:30:00Z"), type: "cv", title: "CV package generated", description: "Tailored CV with 88% match score" },
      { date: new Date("2026-03-31T09:00:00Z"), type: "application", title: "Application submitted", description: "Applied via PwC careers portal" },
      { date: new Date("2026-04-03T09:15:00Z"), type: "email", title: "Acknowledgement received", description: "Application received confirmation from PwC" },
      { date: new Date("2026-04-05T09:00:00Z"), type: "followup", title: "Follow-up #1 sent", description: "Automated follow-up email sent" },
    ],
    notes: [
      { id: "n1", date: new Date("2026-03-31T09:30:00Z"), text: "Strong match -- their digital transformation programme aligns well with my LMS implementation experience." },
      { id: "n2", date: new Date("2026-04-03T10:00:00Z"), text: "Heard back quickly. Good sign. Preparing for possible phone screen." },
    ],
    documents: [
      { name: "CV - PwC Digital Learning Lead.pdf", type: "cv", url: "#" },
      { name: "Cover Letter - PwC.pdf", type: "cover_letter", url: "#" },
    ],
  },
  "b1b2c3d4-0002-4000-8000-000000000002": {
    events: [
      { date: new Date("2026-03-24T14:00:00Z"), type: "discovery", title: "Job discovered", description: "Found via Adzuna -- scored 85 (A tier)" },
      { date: new Date("2026-03-24T14:30:00Z"), type: "cv", title: "CV package generated", description: "Tailored CV with 85% match score" },
      { date: new Date("2026-03-25T14:00:00Z"), type: "application", title: "Application submitted", description: "Applied via recruiter" },
      { date: new Date("2026-03-27T10:00:00Z"), type: "email", title: "Interview scheduled", description: "First round competency interview" },
      { date: new Date("2026-04-01T10:00:00Z"), type: "interview", title: "Interview 1 completed", description: "Competency interview -- went well" },
      { date: new Date("2026-04-03T14:00:00Z"), type: "interview", title: "Interview 2 scheduled", description: "Second round with senior partner" },
    ],
    notes: [
      { id: "n1", date: new Date("2026-04-01T11:00:00Z"), text: "First interview went well. They asked about my experience scaling L&D programmes. Strong rapport with the interviewer." },
    ],
    documents: [
      { name: "CV - KPMG L&D Partner.pdf", type: "cv", url: "#" },
      { name: "Cover Letter - KPMG.pdf", type: "cover_letter", url: "#" },
    ],
  },
};

export const mockScoringRationale: Record<string, {
  overall: number;
  breakdown: { category: string; score: number; maxScore: number; reason: string }[];
}> = {
  "a1b2c3d4-0001-4000-8000-000000000001": {
    overall: 92,
    breakdown: [
      { category: "Title Match", score: 18, maxScore: 20, reason: "'Senior L&D Consultant' directly matches search terms" },
      { category: "Seniority", score: 15, maxScore: 15, reason: "Senior-level aligns with target career level" },
      { category: "Location", score: 14, maxScore: 15, reason: "London, UK -- preferred location" },
      { category: "Salary", score: 13, maxScore: 15, reason: "65-85k range within target 60-90k" },
      { category: "Skills", score: 17, maxScore: 20, reason: "L&D strategy, enterprise clients, change management" },
      { category: "Company", score: 15, maxScore: 15, reason: "Deloitte -- Big 4, strong L&D reputation" },
    ],
  },
  "a1b2c3d4-0003-4000-8000-000000000003": {
    overall: 95,
    breakdown: [
      { category: "Title Match", score: 19, maxScore: 20, reason: "'Head of People Development' matches L&D leadership" },
      { category: "Seniority", score: 15, maxScore: 15, reason: "Head-level role -- career advancement opportunity" },
      { category: "Location", score: 14, maxScore: 15, reason: "London hybrid -- good flexibility" },
      { category: "Salary", score: 15, maxScore: 15, reason: "90-120k exceeds target (stretch opportunity)" },
      { category: "Skills", score: 17, maxScore: 20, reason: "People development, EMEA scope, strategic leadership" },
      { category: "Company", score: 15, maxScore: 15, reason: "Revolut -- high-growth fintech, strong employer brand" },
    ],
  },
  "a1b2c3d4-0002-4000-8000-000000000002": {
    overall: 87,
    breakdown: [
      { category: "Title Match", score: 16, maxScore: 20, reason: "'Learning Experience Designer' partially matches" },
      { category: "Seniority", score: 13, maxScore: 15, reason: "Mid-senior level -- slightly below target" },
      { category: "Location", score: 10, maxScore: 15, reason: "Manchester -- not preferred but acceptable" },
      { category: "Salary", score: 13, maxScore: 15, reason: "55-70k in range but lower end" },
      { category: "Skills", score: 18, maxScore: 20, reason: "Digital learning, experience design, internal L&D" },
      { category: "Company", score: 17, maxScore: 15, reason: "BBC -- prestigious employer, strong L&D function" },
    ],
  },
};

export const mockPrepBriefs: Record<string, {
  companyResearch: string;
  roleInsights: string;
  likelyQuestions: { question: string; starExample: string }[];
  salaryIntelligence: string;
  travelLogistics: string;
}> = {
  "c1b2c3d4-0001-4000-8000-000000000001": {
    companyResearch: "KPMG is one of the Big Four accounting firms with 227,000 employees globally. Their UK L&D function sits within People, Performance & Culture. Recent focus on digital upskilling and ESG capability building. They invested in their KPMG Business School and launched a Digital Academy in 2025.",
    roleInsights: "The L&D Business Partner role reports to the Head of Talent Development. Key focus areas: aligning learning strategy with business priorities, designing blended learning solutions, and measuring learning impact. They're looking for someone who can bridge the gap between business needs and learning solutions.",
    likelyQuestions: [
      { question: "Describe a time you aligned an L&D programme with business strategy", starExample: "Situation: At previous employer, sales team underperforming on new product launches. Task: Design learning intervention tied to business KPIs. Action: Created blended programme with microlearning modules, coaching, and on-the-job practice. Result: 35% improvement in new product revenue within 6 months." },
      { question: "How do you measure the ROI of learning programmes?", starExample: "Situation: Board wanted evidence of L&D investment returns. Task: Build measurement framework. Action: Implemented Kirkpatrick model levels 1-4, created dashboards linking learning completion to performance metrics. Result: Demonstrated 4.2x ROI on leadership programme, secured additional budget." },
      { question: "Tell me about a time you managed a difficult stakeholder", starExample: "Situation: Senior partner resisted mandatory compliance training redesign. Task: Get buy-in for new approach. Action: Presented data on completion rates vs. regulatory risk, offered pilot programme with their team. Result: Partner became champion of the new approach after seeing 95% completion rate." },
    ],
    salaryIntelligence: "KPMG L&D Business Partner roles in London typically range from 65-85k. Given 2+ years experience and Big 4 background, aim for 75-85k. They offer 25 days holiday, private medical, and 7% pension contribution.",
    travelLogistics: "KPMG UK office: 15 Canada Square, London E14 5GL. Canary Wharf tube station (Jubilee line) -- 2 min walk. Allow 45 min from central London. Nearest parking: Canada Square Car Park.",
  },
  "c1b2c3d4-0002-4000-8000-000000000002": {
    companyResearch: "Google has 180,000+ employees globally. Their People Operations team is known for data-driven HR practices. The London office at Pancras Square is their European engineering hub. They've been investing heavily in AI-assisted learning and career development tools.",
    roleInsights: "People Development Lead role focuses on designing and scaling development programmes for engineering and product teams. Reports to VP of People Development EMEA. Emphasis on data-driven approaches, innovation in learning delivery, and cross-cultural programme design.",
    likelyQuestions: [
      { question: "How would you approach designing a development programme for a globally distributed team?", starExample: "Situation: Previous company expanding to 12 countries. Task: Create scalable leadership programme. Action: Designed modular programme with core global content and regional customisation, used async learning for knowledge and live sessions for practice. Result: 92% satisfaction across all regions, 40% reduction in delivery cost." },
      { question: "How do you use data to inform L&D decisions?", starExample: "Situation: L&D budget under scrutiny. Task: Prove value and optimise spending. Action: Built analytics dashboard tracking skill gaps, learning engagement, performance correlation, and business impact. Result: Redirected 30% of budget to high-impact programmes, overall effectiveness score increased 25%." },
    ],
    salaryIntelligence: "Google People Development Lead roles range from 90-130k base plus equity (RSUs worth 30-50k/year). Total compensation could be 120-180k. They offer excellent benefits including free meals, on-site wellness, and generous parental leave.",
    travelLogistics: "Google London: 6 Pancras Square, London N1C 4AG. King's Cross St Pancras station (multiple lines) -- 3 min walk. Interview at reception, Level 4. Ask for Priya Shah (EA to the hiring manager). Allow 40 min from south London.",
  },
};

// Sidebar badge counts
export const mockBadgeCounts = {
  jobs: 5, // new A/B tier jobs
  applications: 8, // active applications
  interviews: 4, // upcoming interviews
  emails: 4, // unread emails
};
